[package]
name = "pixoo_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pixoo_cli"
path = "src/main.rs"

[lib]
name = "pixoo_cli"
path = "src/lib.rs"

[dependencies]
byteorder = "1"
serialport = "4.0.1"
anyhow = "1"
thiserror = "1"

